### PR TITLE
Upgrade eslint and use eslint-config-leapfrog

### PR DESCRIPTION
**Pull request by mesaugat**
* Add `eslint-config-leapfrog`
* Upgrade `babel-eslint` to latest version
* Fix issues reported by eslint
* Update `.travis.yml` to use node `8` only

### CODE REVIEW

**Comment by kabirbaidhya** [comment]
Need to pull master. Also, CI failing, how come?

**Comment by mesaugat** [comment]
Somehow `sqlite3` is having installation problems with node 10 and above.

**Comment by kabirbaidhya** [comment]
@mesaugat Should we just put up to node 8 for the CI then? Or do you get this error in local too?

**Comment by mesaugat** [comment]
It's in local as well.

**Comment by kabirbaidhya** [comment]
Okay, let's go with only node 8 for now. Later we can support 10 when the issue is resolved.

**Pull request merged**
