### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by deepsadhi**
* Statement reorder
* Minimize indentation ladder

### CODE REVIEW

**Comment by pratishshr** [comment]
👍

**Comment by mesaugat** [comment]
Anything more?

**Comment by deepsadhi** [comment]
It may take some more time.

**Comment by mesaugat** [comment]
The proper filename is `chill.yml.dist` and not `chill.dist.yml`. It was fine, we can rename it to `chill.yml.example` if we like to.

**Comment by deepsadhi** [comment]
But if we do that, IDE don't highlight syntax of yml file.

**Pull request merged**
